controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

new_contact:
    path: '/contacts/{idNom}/new'
    controller: App\Controller\ViewContactsController::newContact
    